template: |
  ## Changes

  $CHANGES
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🛠 Fixes
    labels:
      - bug
      - fix
  - title: 🧰 Maintenance
    labels:
      - chore
      - maintenance
change-template: '- $TITLE (#$NUMBER) — @$AUTHOR'
no-changes-template: '- No changes.'
