name: CI

on:
  push:
    branches: [ "main", "master", "chore/ci-fixes", "feat/demo-claims-pass" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (runtime + dev)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r dev-requirements.txt

      - name: Pre-commit (lint/format)
        run: |
          pre-commit install
          pre-commit run --all-files --show-diff-on-failure

      - name: Pytest (repo + proofs)
        run: |
          pytest -q
          pytest -q proofs/
