name: Claim Tests (Demo)

on:
  push:
    branches: [ "feat/demo-claims-pass" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  demo-claims:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run demo claim tests
        run: pytest -q tests/test_claims_demo.py -q
