name: Fuzz (Hypothesis)

on:
  pull_request:
  workflow_dispatch:

jobs:
  fuzz:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up uv (fast pip)
        uses: astral-sh/setup-uv@v3

      - name: Install deps (best effort)
        id: deps
        continue-on-error: true
        run: |
          uv pip install --system --upgrade pip || true
          if [ -f requirements.txt ]; then uv pip install --system -r requirements.txt || true; fi
          if [ -f dev-requirements.txt ]; then uv pip install --system -r dev-requirements.txt || true; fi
          python -c "import hypothesis; print('HYPOTHESIS_OK')" 2>/dev/null || true

      - name: Run Hypothesis robustness (if available)
        id: hyp
        continue-on-error: true
        run: |
          if python -c "import hypothesis" 2>/dev/null; then
            echo "Running Hypothesis suite..."
            pytest -q -k "test_recv_robust and hypothesis"
          else
            echo "Hypothesis not available; skipping property-based tests."
          fi

      - name: Always run lite robustness (no external deps)
        run: |
          pytest -q tests/test_recv_robust_lite.py
