name: Proofs

on:
  push:
    branches: ["main", "master", "feat/demo-claims-pass"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  proofs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run proof tests
        run: pytest -q proofs/ -q
